### ISSUE TITLE
请问会不会开源libkaldi-mace.so代码

### ISSUE THREAD

**Issue by Kangzhiwen** [XiaoMi/mace-kit#3]
您好，我最近在apk中使用libkaldi-mace.so时，因为没有相关的api，我就基于mace-kit中的speech_recognition_test的使用方法，对其进行调用。我再测试的时候发现，libkaldi-mace.so中可能对data文件夹有路径调用，我对data文件进行了几次路径变更，但始终无法调用成功，app错误信息如下：

A/libc: /usr/local/google/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError" failed

**Comment by lu229** [comment]
@Kangzhiwen libkaldi-mace.so的编译可以参见：https://github.com/XiaoMi/mace-kit/tree/master/tool/kaldi#build-kaldi-mace，后续有问题还请继续沟通

**Comment by Kangzhiwen** [comment]
谢谢您的解答。
